<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VAT Number_vat_number</name>
   <tag></tag>
   <elementGuidId>0019789b-b4df-40de-bb44-36eb65d7325e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vat_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vat_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b914204-ff50-4df8-af2e-b4b36127acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23c7ed17-ea9f-4ec4-96ba-0c4576680231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vat_number</value>
      <webElementGuid>d90e9a12-f3ef-4fb4-8561-25f3b0942d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vat_number</value>
      <webElementGuid>ee8f63a2-e850-4980-b99a-ce0429eeb415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9ba98999-5788-4aaf-a945-f52a3f6e67c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>VAT Number</value>
      <webElementGuid>e8a84c19-693c-4109-b521-458a4bebcab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vat_number&quot;)</value>
      <webElementGuid>06088c59-a60e-4f22-9776-6b3cd8311c7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vat_number']</value>
      <webElementGuid>2ae15c4a-a5e7-4687-9a62-71d195d0d9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mwlskmnh']/div/div[11]/div/div/input</value>
      <webElementGuid>f8ec2e22-2804-4dc2-be91-e1b7b44fdd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/input</value>
      <webElementGuid>4ed6a299-1708-4edc-ad92-5391095e8ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vat_number' and @id = 'vat_number' and @placeholder = 'VAT Number']</value>
      <webElementGuid>fb2fb5f2-8b91-4f4c-bb33-0be199453502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
