<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_search</name>
   <tag></tag>
   <elementGuidId>4b3a9c78-ff93-4169-a486-eba0007d6457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.primary-btn.header__search--finding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@class,'btn primary-btn header__search--finding')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc980767-4f8a-40bc-b244-fcf384af0441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn header__search--finding</value>
      <webElementGuid>79149351-41e0-4b37-9cfd-6a41acfe1df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;header&quot;]/div[@class=&quot;grid wide&quot;]/div[@class=&quot;header__with--search&quot;]/div[@class=&quot;header__search--find&quot;]/button[@class=&quot;btn primary-btn header__search--finding&quot;]</value>
      <webElementGuid>479ff2a3-a611-4327-9bad-2739111eb3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div[2]/div[3]/button</value>
      <webElementGuid>bd7794e5-dffa-4f3d-a83c-6b426af47a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần short nam ngắn họa tiết Dri Fit 100% chất dù si thoáng mát, ít nhăn'])[1]/following::button[1]</value>
      <webElementGuid>5dac0a42-a16f-4ce7-91a5-9dc7379370d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần đùi nam, chất liệu vải đũi mềm mát, quần short ngắn kiểu dáng thể thao có dây rút'])[1]/following::button[1]</value>
      <webElementGuid>3d68df27-148a-416d-b9e8-d483bd38c777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các Sản Phẩm Đã Thêm'])[1]/preceding::button[1]</value>
      <webElementGuid>32f374e2-fe6b-4db2-b350-dba9bfad5d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh Mục'])[1]/preceding::button[1]</value>
      <webElementGuid>53592eac-f59b-4b85-8ad5-81c2080cc1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>377242bc-ee60-4b34-81ac-cf51b42b6c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
