<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_search</name>
   <tag></tag>
   <elementGuidId>4b3a9c78-ff93-4169-a486-eba0007d6457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.primary-btn.header__search--finding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/header/div/div[2]/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53d39e5a-ed43-4445-84f6-d4471d5322e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary-btn header__search--finding</value>
      <webElementGuid>6e95eb7e-d739-4660-acc4-b0b4293d92a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;header&quot;]/div[@class=&quot;grid wide&quot;]/div[@class=&quot;header__with--search&quot;]/div[@class=&quot;header__search--find&quot;]/button[@class=&quot;btn primary-btn header__search--finding&quot;]</value>
      <webElementGuid>fbc75b73-4b6b-40f8-82eb-05f5a2f5786e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div[2]/div[3]/button</value>
      <webElementGuid>0ab581d1-56a7-457b-a81a-148718661bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần short nam ngắn họa tiết Dri Fit 100% chất dù si thoáng mát, ít nhăn'])[1]/following::button[1]</value>
      <webElementGuid>0e35a964-06dc-43c8-b569-35a19c82c86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần đùi nam, chất liệu vải đũi mềm mát, quần short ngắn kiểu dáng thể thao có dây rút'])[1]/following::button[1]</value>
      <webElementGuid>e3381945-c38a-48f6-8f95-300df8981222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Các Sản Phẩm Đã Thêm'])[1]/preceding::button[1]</value>
      <webElementGuid>41065d85-28c0-4a33-a6ac-033a3b5590a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Danh Mục'])[1]/preceding::button[1]</value>
      <webElementGuid>8bfbdf4d-86d8-4980-b38e-61365343589a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>41461354-d625-4a98-b694-23ee28989699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
