<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search</name>
   <tag></tag>
   <elementGuidId>6bf14d80-76c4-4ac3-aac1-bbf5d5b7150a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.header__search-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a52b2b10-3fa4-4575-858b-6fbdcd7e151c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d2f6e9d-f9a5-4aef-83c7-08aadc7b0bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header__search-text</value>
      <webElementGuid>4b550d60-9e31-48e7-b46e-5df9b31e2120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập để tìm kiếm</value>
      <webElementGuid>fc7fea27-0e06-4936-a49d-b00566a19f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/header[@class=&quot;header&quot;]/div[@class=&quot;grid wide&quot;]/div[@class=&quot;header__with--search&quot;]/div[@class=&quot;header__search--find&quot;]/div[@class=&quot;header__search--filler&quot;]/input[@class=&quot;header__search-text&quot;]</value>
      <webElementGuid>1d60827f-cf69-4913-a473-0ea30d8d107e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>aa1e1298-9f0d-41f4-a6a9-da76bfaa03d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/header/div/div[2]/div[3]/div/input</value>
      <webElementGuid>66ba56a2-7028-45bb-9eb0-a2e07bf368f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3479e099-a8fd-429e-acba-c701a5691a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nhập để tìm kiếm']</value>
      <webElementGuid>05c08f4f-afe9-47a8-a0cb-7af001d1b99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
