<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_STORE</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>588a40c9-2567-4a84-9e51-e60fd9691731</testSuiteGuid>
   <testCaseLink>
      <guid>85490ba2-be97-4d1e-bafd-4aa884e77c02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_Web/Login_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c4050c00-fd36-47f6-9603-a5de08ba3151</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4312e1da-91c2-492c-82b4-5f93b101bf9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cce2d00-59f9-4c97-ac8a-e8a3a84f088a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3b440c1-2d05-4a16-9379-7a45f45aa5f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_Web/Login_fail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be0fadf8-fb63-462e-ad2d-937a5267e935</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22e74993-3660-4dd5-8530-d6fde80250ee</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
