<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Blogger_Framename1</name>
   <tag></tag>
   <elementGuidId>322661f8-a1a0-420b-806b-c9b69fd15d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Frame1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Frame1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cb6de014-8160-4cf9-964e-59d7719e06d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200px</value>
      <webElementGuid>c8e79dfb-7a74-44f6-849d-1fdd686e0e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100px</value>
      <webElementGuid>7ff1af85-df1d-4c8a-a736-307fb15949b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Frame1</value>
      <webElementGuid>60c9a79a-ff63-4e6f-8f5b-2ef0d0fb41d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Framename1</value>
      <webElementGuid>0e88c8d2-8547-475c-9deb-fba5b1763ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>about:blank</value>
      <webElementGuid>0a8f1c85-66a5-4d88-8703-c408d2099845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Frame1&quot;)</value>
      <webElementGuid>77ed2a3c-337b-4cd3-bff6-eb472494ae51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Frame1']</value>
      <webElementGuid>513f5c6d-ed8a-4c6f-85e2-c19bafabd007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='regform']/div/iframe</value>
      <webElementGuid>f5774b27-1ae9-4d35-a47b-c606982bf50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>875c945e-168e-4c67-aae4-db7f3f2b5bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'Frame1' and @name = 'Framename1' and @src = 'about:blank']</value>
      <webElementGuid>bd158410-0660-405a-998c-da81ac249d5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
