<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Currency Symbol_currency_symbol</name>
   <tag></tag>
   <elementGuidId>d6a20c92-e8ce-4d90-b286-cd710e78b117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currency_symbol</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='currency_symbol']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa677ffd-567f-4c28-bd9b-0173e683a0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88c6d9dc-4944-444d-9a87-3bea96e7c1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency_symbol</value>
      <webElementGuid>167d50f6-1648-486c-b03b-c69ac0797639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency_symbol</value>
      <webElementGuid>c4048024-4ec8-4c00-af73-bcf07911e282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>958e04ec-cfa0-42dc-81ee-df6f64cf5bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keep it blank to use the default ($)</value>
      <webElementGuid>c43470d4-808e-4a51-8440-0a4b0b544e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currency_symbol&quot;)</value>
      <webElementGuid>faf07c80-230c-439d-8103-5fcfe09a16cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currency_symbol']</value>
      <webElementGuid>1ab58838-66b5-4c43-aa7a-5ccfebfa3d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mwlskmnh']/div/div[15]/div/div/input</value>
      <webElementGuid>f11de7c7-5015-4a59-aca5-db492a96b342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div/input</value>
      <webElementGuid>65c7f210-413c-4808-b384-0caf2fdd8c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currency_symbol' and @id = 'currency_symbol' and @placeholder = 'Keep it blank to use the default ($)']</value>
      <webElementGuid>dc2aa478-c0fa-4a10-895c-b94b96747919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
