<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GST Number_gst_number</name>
   <tag></tag>
   <elementGuidId>ceed8b58-6046-49b4-bd0d-ba4db5dd451e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gst_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gst_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd0dd586-60e8-4e31-a4d4-ae04a841ed93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a3d6a27-4282-4d92-9aab-01a8d81ee167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gst_number</value>
      <webElementGuid>c99705a3-ed68-4192-aec5-2eb135c646fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gst_number</value>
      <webElementGuid>2a9a3d2a-5438-4ffc-9ddf-70bba1047021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea61d633-edda-45f8-b277-2248c148d67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>GST Number</value>
      <webElementGuid>db4828fb-c818-4960-bf1d-de1cc3949db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gst_number&quot;)</value>
      <webElementGuid>2639e704-abc7-4137-983f-dd924ea66536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gst_number']</value>
      <webElementGuid>3561fcbe-72ee-4b5e-8311-5164f553cba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mwlskmnh']/div/div[12]/div/div/input</value>
      <webElementGuid>02cd192b-8f8a-42d9-9558-ce73a8f14857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/input</value>
      <webElementGuid>39c78943-f7b3-4131-8df2-ad09a5eac9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'gst_number' and @id = 'gst_number' and @placeholder = 'GST Number']</value>
      <webElementGuid>0c9d1fbf-bc56-4d4c-be67-fab524e9cc03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
