<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_muahang</name>
   <tag></tag>
   <elementGuidId>b9291910-8fcd-4e08-b6ac-e50dc598c064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div/div/div[2]/div[5]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e2b3e25-70fe-49ee-b30f-589138cc8bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-info__caculator--cart btn </value>
      <webElementGuid>9a96ecaf-2409-4684-bee8-10f635ae86ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mua Hàng</value>
      <webElementGuid>e82345d6-bab6-44ba-a812-cfec1f96a8f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-detail&quot;]/div[@class=&quot;grid wide&quot;]/div[@class=&quot;row small-gutter  app__content&quot;]/div[@class=&quot;product__content&quot;]/div[@class=&quot;change-wrap&quot;]/div[@class=&quot;product-info&quot;]/div[@class=&quot;product-info__caculator&quot;]/button[@class=&quot;product-info__caculator--cart btn&quot;]</value>
      <webElementGuid>4eb65b00-1037-4e12-97ca-e57972fbfc43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div[2]/div[5]/button[2]</value>
      <webElementGuid>23c6c76d-e1f2-45af-974b-4301a53b4f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm Vào Giỏ Hàng'])[1]/following::button[1]</value>
      <webElementGuid>302e4acf-8c4c-423d-b54f-022d60e68d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm có sẵn'])[1]/following::button[2]</value>
      <webElementGuid>377d5c7d-3984-40df-9f3f-5a20b94e0c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tài trợ bởi DN Store 💙'])[1]/preceding::button[1]</value>
      <webElementGuid>5085512b-1776-4880-837b-1febf841b43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm đánh giá'])[1]/preceding::button[1]</value>
      <webElementGuid>e03c54eb-374c-4552-9b73-73841fc8fc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mua Hàng']/parent::*</value>
      <webElementGuid>4ccd7302-19aa-4654-983d-2ada626ceaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>dd8b0f4e-05e5-4b70-8e8c-7e2b12c86bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Mua Hàng' or . = 'Mua Hàng')]</value>
      <webElementGuid>27b1f452-c0c3-489d-9799-9bfdd0f148e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
