<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>8445868f-23ba-4ab1-8351-443943253407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.product-info__caculator--plus > input[type=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ac997d9-490c-4352-bbc3-14576134ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41d734a7-0a75-419a-a9d5-b14aeec49a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>780fe069-e6c7-4090-b802-16258fac7ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-detail&quot;]/div[@class=&quot;grid wide&quot;]/div[@class=&quot;row small-gutter  app__content&quot;]/div[@class=&quot;product__content&quot;]/div[@class=&quot;change-wrap&quot;]/div[@class=&quot;product-info&quot;]/div[@class=&quot;product-info__caculator&quot;]/div[@class=&quot;product-info--wrap&quot;]/div[@class=&quot;product-info__caculator--plus&quot;]/input[1]</value>
      <webElementGuid>6ac68d3d-1571-42e5-9f36-b42d1c340b88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
      <webElementGuid>ef0886ab-1872-4f42-a8b4-66677f2ffa52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div/div/div[2]/div[5]/div/div[2]/input</value>
      <webElementGuid>6135bb88-15e1-4c4a-90e8-4c468466daf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>6baec4e5-9328-49dc-b062-354ff05e3d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>39791df8-c08c-4961-9efb-d9d797561136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
