<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_You pressed Cancel</name>
   <tag></tag>
   <elementGuidId>e60d1a81-d6a9-4ca2-aa42-ce874cfd5373</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Parademo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='Parademo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>248a764a-cd1a-4c2c-a311-ec7aa369a08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Parademo</value>
      <webElementGuid>fa1d860f-c892-41f6-9abb-28a50ffd5976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>36898cba-d98a-4913-bafe-be4e3cdd4b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You pressed Cancel!</value>
      <webElementGuid>304a303d-20a1-47f3-ace6-9fae95a620c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Parademo&quot;)</value>
      <webElementGuid>c263bf86-bf6c-4809-bbc7-21b110f4f2b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='Parademo']</value>
      <webElementGuid>45fda028-405c-4151-b489-ae3f88222d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='regform']/div/b/p</value>
      <webElementGuid>73c35676-56d4-44f5-918f-e323668ac077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different Types of ALERTS!'])[1]/following::p[1]</value>
      <webElementGuid>07b06ec8-9f58-40f5-a265-6da0551f04dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Dummy Controls]'])[1]/following::p[1]</value>
      <webElementGuid>fcbdf5a0-b403-41f7-a0e9-9c2220a980a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qavalidation'])[1]/preceding::p[1]</value>
      <webElementGuid>e294a518-d4d3-4130-b5be-a4f01e053d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qavbox'])[1]/preceding::p[1]</value>
      <webElementGuid>2f84d46d-efd1-4112-8ac9-ccd4c7d370ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You pressed Cancel!']/parent::*</value>
      <webElementGuid>16f3dc32-521e-4f89-9da1-5b5c55999906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>0f825be2-c504-4aad-ba3d-c548a77fd346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'Parademo' and (text() = 'You pressed Cancel!' or . = 'You pressed Cancel!')]</value>
      <webElementGuid>bfcf036a-0e38-4ce4-b9bd-47d7dbee6579</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
