<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select Sunday  Monday  Tuesda_3c4b3e</name>
   <tag></tag>
   <elementGuidId>6d7cfe68-46e6-47ed-b660-334911802170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='select-demo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-demo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6a40ed57-90e4-474f-86b2-9ca6b8e69ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6ce0cdee-ee2b-4087-9f1f-0195f0cfcc72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select-demo</value>
      <webElementGuid>3525c7f3-3f6f-4765-ac05-4ead72f66415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Please select
				 Sunday
				  Monday
				  Tuesday
				  Wednesday
				  Thursday
				  Friday
				  Saturday
			  </value>
      <webElementGuid>934d5791-ca62-433c-bb5b-824730707adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-demo&quot;)</value>
      <webElementGuid>73e60e7b-b5fd-4246-a22a-d7eb53ac4f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='select-demo']</value>
      <webElementGuid>aed2dda3-e915-4ec8-93a0-1e85e782a962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='easycont']/div/div[2]/div/div[2]/select</value>
      <webElementGuid>22adbe0a-ed10-4f46-8244-de37013a4df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a day (select one):'])[1]/following::select[1]</value>
      <webElementGuid>dd0bd94d-cabb-490e-96a4-833d1c25e1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select List Demo'])[1]/following::select[1]</value>
      <webElementGuid>ecf38742-fba3-4475-95c2-bd087b1ccde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Select List Demo'])[1]/preceding::select[1]</value>
      <webElementGuid>bdb51c1f-0a19-44e2-bed4-68113c03d055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Selected'])[1]/preceding::select[2]</value>
      <webElementGuid>df22954b-aed6-4738-81dc-64fab1b2e6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4b5e20b8-ff9d-48e6-bf9f-3623998008c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'select-demo' and (text() = '
				Please select
				 Sunday
				  Monday
				  Tuesday
				  Wednesday
				  Thursday
				  Friday
				  Saturday
			  ' or . = '
				Please select
				 Sunday
				  Monday
				  Tuesday
				  Wednesday
				  Thursday
				  Friday
				  Saturday
			  ')]</value>
      <webElementGuid>86da1b0b-a9c3-4772-8e02-9f1f23349aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
