<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Click Button to see alert</name>
   <tag></tag>
   <elementGuidId>8d2b9af2-ca8f-4387-8ce6-cff7627d824c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='javascriptAlertsWrapper']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#javascriptAlertsWrapper > div.row > div.col-md-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5617b53-b124-4366-8661-e460efa9da8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6</value>
      <webElementGuid>19b030c0-613f-43e0-b519-531bc45bc382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click Button to see alert </value>
      <webElementGuid>d42910fe-8c4e-48ab-8385-9eacdb4fc76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;javascriptAlertsWrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]</value>
      <webElementGuid>52ab8977-606e-4bf1-9e1d-d8a32c3dff23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='javascriptAlertsWrapper']/div/div</value>
      <webElementGuid>a03421d6-500c-43d5-8c7c-6acf79519955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Store API'])[1]/following::div[6]</value>
      <webElementGuid>a2c620e0-cd4d-4be5-a860-5ce5ff90e8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[6]</value>
      <webElementGuid>7008699b-1ee4-4b72-b13a-8ee0a06bb1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[1]/preceding::div[1]</value>
      <webElementGuid>b25b7118-c378-4fbb-9141-be6e40908e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div</value>
      <webElementGuid>da6027ce-1509-41d2-9d5f-fe84056e2f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Click Button to see alert ' or . = 'Click Button to see alert ')]</value>
      <webElementGuid>6f36254e-2637-4f50-ad96-0a8ead1d610c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
